access_log/ChildErrorLog: remove "noexcept" because it breaks with GCC 4.9
Work around bogus error:

 access_log/ChildErrorLog.cxx:41:1: error: function 'ChildErrorLog::ChildErrorLog()' defaulted on its redeclaration with an exception-specification that differs from the implicit declaration 'ChildErrorLog::ChildErrorLog()'