rerror: move code to ToResponse(std::exception_ptr)
Also remove parameters "status" and "msg" from
response_dispatch_log(), as they're not needed anymore.  The whole
function was unused, so we can easily change the API.